### PR TITLE
Make sure useFetch rejects with an Error type.

### LINKED ISSUE #113: useFetch should reject with an Error object
Right now, if there's a request error, parseResponse from `useFetch` rejects with the response object instead of with an Error object. This causes two difficulties:
- rejecting with a non-Error means you don't have a full stack trace
- it contradicts the AsyncState type, so if you try to use state.error in TypeScript you have to cast it through unknown, i.e. `((error as unknown) as Response)`. (The intermediate step is necessary because Error and Response are unrelated types.)

The best fix is probably to change useFetch to throw an Error object that has a handle to the underlying response, which is unfortunately a backward-incompatible change. The other possibility I can think of is to widen or parameterize the error type, but I'm not sure it's a good idea to make the signature more complicated to support something that's not a great practice (i.e. throwing non-errors).

### PR DESCRIPTION
**Pull request by artdent**
# Description

Failed http responses in `useFetch` now reject with a FetchError,
with the underlying Response object available as error.response.

Previously, a non-ok http response would reject with the response
object directly. It's better for rejections to be of type Error
so that the full stack trace information is available; plus, the
TypeScript type definition assumes that the error object is always
instanceof Error.

Fixes #113.

## Breaking changes

The `error` property of the state object returned by `useFetch`
is no longer a Response object. If you need the response object,
replace references to `state.error` with `state.error.response`.

# Checklist

- [x] Added / updated the unit tests
- [ ] Added / updated the documentation
- [x] Updated the TypeScript type definitions

### CODE REVIEW

File: packages/react-async/src/useAsync.js [hunk 1]
```diff
@@ -154,8 +154,15 @@ const useAsync = (arg1, arg2) => {
   )
 }
 
+export class FetchError extends Error {
+  constructor(response) {
+    super(response.statusText)
```
Comment (ghengeveld) [inline packages/react-async/src/useAsync.js]: I'd like to have the `status` code prepended here, joined with a space. It makes it a little easier to see it originates from an HTTP request. I also think in some situations there is no `statusText`, but I'm not sure.

Comment (artdent) [reply packages/react-async/src/useAsync.js]: Done. I think that statusText should be populated in all cases where fetch itself doesn't throw; if not, it appears to default to '', which isn't ideal but isn't terrible.

**Comment by artdent** [comment]
Thanks for the review! I added one more small commit to fix an issue I ran into trying to actually use FetchError in client code.

The CI failure looks spurious, but I haven't dug in...

**Comment by ghengeveld** [comment]
Looking good. Thanks!

I'll look into what's causing CodeSandbox CI to fail. It's something I added very recently and it's still in closed beta. We are early adopters 😅
